language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: JiSmZ+3/6g6Q1xfKt3/7yrSzNKUqfTlWlgQiFFT1UhyzF3Yjgr0y17wnZBLCxsJWmmyay0lyfhTrDC01ZXjdacIMQmTTlVYxAV17OERhP2pVJKz8vneClzWQ+LBWU+nhMHrggp0ocaqenTQ935piQdUazc7sixs0yi3yvzVUy5ChnQMFh3XVjQUZhoxrrpcsbs56K6Lh6pFiGhdXTgHy2nsFZulsYuR77439dU0lvsJiHuKpoUatMuCMQd6vjCZOyhIJEJ/ipxKeRtXf3B/IYX5bXvms9+Cf88ZEPjn/O7fL4FZLlF/CBx6RLpJvrXwVXmyLcoQjZyK7ZH3GXDG+LwAziJgeo2de5rdxIwlki6Q4a905+G+p7xZ6RwSHLRHnu/tBOLhJcCilWzhJyCcr866AUf/bikctzAdd5lE1blc+P49mPIufkbmChEOC1ECtFPk3Bmk3SofohejB8kJ+4aT/R4Hz3ruvvCZZIYiK+ZoOO6pYmciK9E+raPFH+UeczGgLikbbdLHKyHfWy0/jyI8zgfYGDUPKtoxwuYvCCiqkBWHcSV7smI1Kt9jdLv0YQ5LXEslThvawmqnLtgm5ou+X3zYBNIyXqEhwK8zyc043Oje6Rf3wfvv3UVdhWZuGfd1lkTwpAq45Ro4KkUx0S/UB+hFTzRE/D8FwUQ36IHM=
  app: delicieux-panel
cache:
  directories:
  - node_modules
