language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: sPei8LCq0/jygR4F6Rb82LXE8qDu6kroT561h2qwZr/PUl9z4s3bx0Cf+nW2qUWYIi/Kx9YxxicXGZ/86O/I7hIMLedgX3II4AG2gAJDMNvq5he8Zzozag4C5ewrjcHE7nht3DsXxOlC3Mf2x0my99zdXoO773lN4Rb1d64zxH3cbJsqVfkt3mZTeu9nAGASf6lYiUtrTWlXWqEUI3kJwjMFUoHh+563Dvjt+bTjOeZ5rxYc8w7XP2tGvMPsaRPPF5dD+yDLYa5KiAHYn4hJcrZ1eKHlLg2gIqVImRBC3TMeWK/yIOV10WUzstpIiung+QCq+eHuHUrD3GtkAKhWrK2RoASw80Gg0LXi4NwG7rBtgaf9NJvyaz6HkThQKYp+JLAybLKXuqbwQLYLoF2uXI6Xcui/S7J1J3BrvwxmuDElkmKc+hcQ31ImP7/0hSnFfPD5kY82VRqPIUz5G0wwQb4JA69gxVa4M+Uh77GfbeRrOrVPEedJuegzgJO3Was6ZEsaLt+5YiqTP9orme0QUtqdmqfokyFCmPsbW79U0gnGDY6BsqEm3+xt/9RIKcK00UT2nqpNXv/YMo5srfU/NuDnrBW2RPihkNx0+oGhzVSt0l2PUBhHgs1p46WhnKPNeutVagKvC4PNzyTtISXSD44mZcI04XfSS2aIlW9MHoM=
  app: delicieux-panel
cache:
  directories:
  - node_modules
